language: node_js
node_js:
  - "6.11"
cache:
  directories:
  - node_modules
branches:
  only:
    - master

before_script:
  - yarn global add firebase-tools
  - yarn

script:
  - yarn run build

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN} --non-interactive
