language: node_js
node_js:
  - "6.11"

branches:
  only:
    - master

before_script:
  - yarn global firebase-tools
  - yarn

script:
  - yarn run build

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}
